### ISSUE TITLE
[regression] impossible to build digitransit

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/digitransit-ui#1296]
Since February 2nd, it is not possible to build digitransit anymore. Here is the log:

/var/www/transports/digitransit-ui-paris/webpack.config.js:114
  let logo = config.favicon || './sass/themes/' + config.CONFIG + '/favicon.png';
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at requireConfig (/var/www/transports/digitransit-ui-paris/node_modules/webpack/bin/convert-argv.js:96:18)
    at /var/www/transports/digitransit-ui-paris/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)

Please fix :)

**Comment by kalon33** [comment]
@samuliheljo @hannesj @Macroz I don't understand why that fails. Shouldn't that be automatically tested when committing?

**Comment by kalon33** [comment]
OK, so I found the culprit. I was using default node version in Ubuntu 14.04LTS, after updating to latest node LTS version (built from source) that fixed the problem. Digitransit build time seems much longer though. Is that expected?

**Comment by kalon33** [comment]
Rebuilding it now I do not experience slow down anymore. Closing.
