### ISSUE TITLE
Digitransit crashes since module updates

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/digitransit-ui#2016]
Since latest module updates, I encountered that error, that make DT crashing:

```
yarn run v1.3.2
warning package.json: License should be a valid SPDX license expression
$ NODE_ENV=production node $NODE_OPTS server/server
Digitransit-ui available on port 7812
fetch timeout
/var/www/transports/digitransit-ui-paris/node_modules/react-relay/lib/throwFailedPromise.
s:24
      throw error;
      ^

Error: fetch timeout
    at Object.<anonymous> (/var/www/transports/digitransit-ui-paris/node_modules/react-re
ay-network-layer/lib/middleware/retry.js:9:20)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/var/www/transports/digit
ansit-ui-paris/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/transports/digitransit-ui-paris/node_modules/react-re
ay-network-layer/lib/index.js:16:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any idea for a fix? @hannesj before your new module updates merges, I didn't experience that, especially fetch timeout errors weren't critical and did not crashed DT...

Thanks for your help.

Edit: both errors were identical... sorry for not noticing it before.

**Comment by hannesj** [comment]
Should be fixed now
