### ISSUE TITLE
png-img error

### ISSUE THREAD

**Issue by marti1959it** [HSLdevcom/digitransit-ui#3359]
I'm trying to install digitransit-ui on a **CentOS 7** machine (7.8.2003 core) featuring:

- **node v14.4.0** (npm 6.14.5)
- **gcc 9.1.0**

Installation aborts: could this be a node.js-module or a gcc related issue?

```
[root@otp-dev digitransit-ui]# yarn install
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "workspace-aggregator-e3926062-e4ac-4fd0-a673-aba87d8d689e > isomorphic-relay-router@0.8.6" has incorrect peer dependency "isomorphic-relay@https://github.com/michaelstockton/isomorphic-relay.git#feature-relay-1-public".
warning "workspace-aggregator-e3926062-e4ac-4fd0-a673-aba87d8d689e > isomorphic-relay-router@0.8.6" has incorrect peer dependency "react@^15.0.1".
warning "enzyme-adapter-react-16 > react-test-renderer@16.13.1" has incorrect peer dependency "react@^16.13.1".
warning "eslint-config-airbnb > eslint-config-airbnb-base@13.2.0" has incorrect peer dependency "eslint-plugin-import@^2.17.2".
[5/5] Building fresh packages...
[6/12] ⠁ polyfill-library
[2/12] ⠁ node-zopfli-es
[10/12] ⠁ iltorb
[4/12] ⠁ phantomjs-prebuilt
error /app/otp-utilities/digitransit-ui/node_modules/png-img: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /app/otp-utilities/digitransit-ui/node_modules/png-img
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@14.4.0 | linux | x64
gyp http GET https://nodejs.org/download/release/v14.4.0/node-v14.4.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v14.4.0/node-v14.4.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v14.4.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v14.4.0/SHASUMS256.txt
gyp info spawn /bin/python2
gyp info spawn args [
gyp info spawn args   '/app/otp-utilities/digitransit-ui/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/app/otp-utilities/digitransit-ui/node_modules/png-img/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/app/otp-utilities/digitransit-ui/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/14.4.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/14.4.0',
gyp info spawn args   '-Dnode_gyp_dir=/app/otp-utilities/digitransit-ui/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/14.4.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/app/otp-utilities/digitransit-ui/node_modules/png-img',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/app/otp-utilities/digitransit-ui/node_modules/png-img/build'
  CC(target) Release/obj.target/libpng/third_party/libpng/png.o
make: cc: Command not found
make: *** [Release/obj.target/libpng/third_party/libpng/png.o] Error 127
make: Leaving directory `/app/otp-utilities/digitransit-ui/node_modules/png-img/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/app/otp-utilities/digitransit-ui/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 3.10.0-1062.1.2.el7.x86_64
gyp ERR! command "/usr/bin/node" "/app/otp-utilities/digitransit-ui/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /app/otp-utilities/digitransit-ui/node_modules/png-img
gyp ERR! node -v v14.4.0
```

**Comment by marti1959it** [comment]
Oops! Resolved with setting the CC environment variable:
$>export CC="gcc"
