### ISSUE TITLE
yarn build error

### ISSUE THREAD

**Issue by marti1959it** [HSLdevcom/digitransit-ui#3371]
I'm trying to **build** digitransit-ui (the most recent version) on a CentOS 7 machine (7.8.2003 core) featuring:

node v10.21 (npm 6.14.4)
gcc 9.1.0
yarn 1.22.4

The app works fine with `yarn run dev`, but `yarn run build` crashes:
 
```
yarn run v1.22.4
$ yarn run static
$ mkdir -p _static/js; mkdir -p _static/css; cp -r static/* _static
$ NODE_ENV=production node --max_old_space_size=4096 node_modules/.bin/webpack --progress --color --display-error-d                                                   etails
10% building 1/1 modules 0 activeevents.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:78:25)
    at writevGeneric (internal/stream_base_commons.js:67:3)
    at Socket._writeGeneric (net.js:712:5)
    at Socket._writev (net.js:721:8)
    at doWrite (_stream_writable.js:413:12)
    at clearBuffer (_stream_writable.js:522:5)
    at Socket.Writable.uncork (_stream_writable.js:319:7)
    at Socket.Writable.end (_stream_writable.js:589:10)
    at Socket.end (net.js:545:31)
    at writeBufferInChunks (/app/otp-utilities/digitransit-ui/node_modules/svg2png/lib/svg2png.js:41:20)
    at module.exports (/app/otp-utilities/digitransit-ui/node_modules/svg2png/lib/svg2png.js:13:5)
    at Object.nearest (/app/otp-utilities/digitransit-ui/node_modules/favicons/helpers-es5.js:302:25)
    at /app/otp-utilities/digitransit-ui/node_modules/favicons/es5.js:61:37
    at fn (/app/otp-utilities/digitransit-ui/node_modules/favicons/node_modules/async/lib/async.js:746:34)
    at /app/otp-utilities/digitransit-ui/node_modules/favicons/node_modules/async/lib/async.js:1213:16
    at /app/otp-utilities/digitransit-ui/node_modules/favicons/node_modules/async/lib/async.js:166:37
    at /app/otp-utilities/digitransit-ui/node_modules/favicons/node_modules/async/lib/async.js:706:43
    at /app/otp-utilities/digitransit-ui/node_modules/favicons/node_modules/async/lib/async.js:167:37
    at Object.async.waterfall (/app/otp-utilities/digitransit-ui/node_modules/favicons/node_modules/async/lib/async                                                   .js:710:44)
    at createFavicon (/app/otp-utilities/digitransit-ui/node_modules/favicons/es5.js:60:23)
    at /app/otp-utilities/digitransit-ui/node_modules/favicons/es5.js:108:24
    at Object.async.forEachOf.async.eachOf (/app/otp-utilities/digitransit-ui/node_modules/favicons/node_modules/as                                                   ync/lib/async.js:233:13)
    at createFavicons (/app/otp-utilities/digitransit-ui/node_modules/favicons/es5.js:107:19)
    at /app/otp-utilities/digitransit-ui/node_modules/favicons/es5.js:118:24
    at /app/otp-utilities/digitransit-ui/node_modules/favicons/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/app/otp-utilities/digitransit-ui/node_modules/favicons/node_modules/async/lib                                                   /async.js:233:13)
    at _parallel (/app/otp-utilities/digitransit-ui/node_modules/favicons/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/app/otp-utilities/digitransit-ui/node_modules/favicons/node_modules/async/lib/async.                                                   js:731:9)
    at createPlatform (/app/otp-utilities/digitransit-ui/node_modules/favicons/es5.js:117:19)
    at /app/otp-utilities/digitransit-ui/node_modules/favicons/es5.js:135:21
    at Object.async.forEachOf.async.eachOf (/app/otp-utilities/digitransit-ui/node_modules/favicons/node_modules/as                                                   ync/lib/async.js:233:13)
    at createOffline (/app/otp-utilities/digitransit-ui/node_modules/favicons/es5.js:131:19)
    at create (/app/otp-utilities/digitransit-ui/node_modules/favicons/es5.js:178:90)
    at /app/otp-utilities/digitransit-ui/node_modules/favicons/es5.js:184:20
    at fn (/app/otp-utilities/digitransit-ui/node_modules/favicons/node_modules/async/lib/async.js:746:34)
    at /app/otp-utilities/digitransit-ui/node_modules/favicons/node_modules/async/lib/async.js:1213:16
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:430:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at Socket._destroy (net.js:614:3)
    at Socket.destroy (internal/streams/destroy.js:37:8)
    at afterWriteDispatched (internal/stream_base_commons.js:78:17)
    at writevGeneric (internal/stream_base_commons.js:67:3)
    [... lines matching original stack trace ...]
    at /app/otp-utilities/digitransit-ui/node_modules/favicons/es5.js:135:21
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Being unexperienced in building Node applications, a hint would be appreciated.
Thanks
Roberto

**Comment by marti1959it** [comment]
Resolved installing **fontconfig** as hinted in:
 https://stackoverflow.com/questions/45129742/error-while-loading-shared-libraries-libfontconfig-so-1-on-cent-os

`yum install fontconfig`

Roberto
