### ISSUE TITLE
Unable to run yarn install according to Installation.md

### ISSUE THREAD

**Issue by dancesWithCycles** [HSLdevcom/digitransit-ui#4151]
Hi folks,
How are you doing? I thank you very much creating and maintaining this repository. Please accept my appreciation!

I am following the [Installation.md](https://github.com/HSLdevcom/digitransit-ui/blob/master/docs/Installation.md) documentation with the goal to build and run a customized version of `digitransit-ui`.

My build environment is the following.

```
~/git/digitransit-ui$ node -v
v14.16.0
~/git/digitransit-ui$ npm -v
7.7.5
~/git/digitransit-ui$ yarn --version
1.22.10
~/git/digitransit-ui$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
```
When I call the instruction `yarn install` I receive the following error. I appreciate any advice pointing me in the right direction. Cheers! 

```
~/git/digitransit-ui$ yarn install
yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "workspace-aggregator-6d31fee4-23a1-4d0e-9e20-8d0bdd692ee7 > isomorphic-relay-router@0.8.6" has incorrect peer dependency "isomorphic-relay@https://github.com/michaelstockton/isomorphic-relay.git#feature-relay-1-public".
warning "workspace-aggregator-6d31fee4-23a1-4d0e-9e20-8d0bdd692ee7 > isomorphic-relay-router@0.8.6" has incorrect peer dependency "react@^15.0.1".
warning "enzyme-adapter-react-16 > react-test-renderer@16.13.1" has incorrect peer dependency "react@^16.13.1".
warning "eslint-config-airbnb > eslint-config-airbnb-base@13.2.0" has incorrect peer dependency "eslint-plugin-import@^2.17.2".
[5/5] Building fresh packages...
[-/12] ⠁ waiting...
[-/12] ⠁ waiting...
[10/12] ⠂ iltorb
[11/12] ⠂ node-sass
error /home/stefan/git/digitransit-ui/node_modules/png-img: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/stefan/git/digitransit-ui/node_modules/png-img
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.0.0
gyp info using node@14.16.0 | linux | x64
gyp info find Python using Python version 3.6.9 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/stefan/git/digitransit-ui/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/stefan/git/digitransit-ui/node_modules/png-img/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/stefan/git/digitransit-ui/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/stefan/.cache/node-gyp/14.16.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/stefan/.cache/node-gyp/14.16.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/stefan/git/digitransit-ui/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/stefan/.cache/node-gyp/14.16.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/stefan/git/digitransit-ui/node_modules/png-img',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/stefan/git/digitransit-ui/node_modules/png-img/build'
  CC(target) Release/obj.target/libpng/third_party/libpng/png.o
  CC(target) Release/obj.target/libpng/third_party/libpng/pngerror.o
  CC(target) Release/obj.target/libpng/third_party/libpng/pngget.o
  CC(target) Release/obj.target/libpng/third_party/libpng/pngmem.o
  CC(target) Release/obj.target/libpng/third_party/libpng/pngpread.o
  CC(target) Release/obj.target/libpng/third_party/libpng/pngread.o
../third_party/libpng/pngread.c: In function ‘png_create_colormap_entry’:
../third_party/libpng/pngread.c:1905:38: warning: this statement may fall through [-Wimplicit-fallthrough=]
                entry[afirst ? 0 : 3] = (png_byte)alpha;
                ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
../third_party/libpng/pngread.c:1906:13: note: here
             case 3:
             ^~~~
../third_party/libpng/pngread.c:1913:34: warning: this statement may fall through [-Wimplicit-fallthrough=]
                entry[1 ^ afirst] = (png_byte)alpha;
                ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
../third_party/libpng/pngread.c:1914:13: note: here
             case 1:
             ^~~~
  CC(target) Release/obj.target/libpng/third_party/libpng/pngrio.o
  CC(target) Release/obj.target/libpng/third_party/libpng/pngrtran.o
../third_party/libpng/pngrtran.c: In function ‘png_set_crc_action’:
../third_party/libpng/pngrtran.c:50:10: warning: this statement may fall through [-Wimplicit-fallthrough=]
          png_warning(png_ptr,
          ^~~~~~~~~~~~~~~~~~~~~
             "Can't discard critical data on CRC error");
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../third_party/libpng/pngrtran.c:52:7: note: here
       case PNG_CRC_ERROR_QUIT:                                /* Error/quit */
       ^~~~
  CC(target) Release/obj.target/libpng/third_party/libpng/pngrutil.o
  CC(target) Release/obj.target/libpng/third_party/libpng/pngset.o
  CC(target) Release/obj.target/libpng/third_party/libpng/pngtest.o
  CC(target) Release/obj.target/libpng/third_party/libpng/pngtrans.o
  CC(target) Release/obj.target/libpng/third_party/libpng/pngwio.o
  CC(target) Release/obj.target/libpng/third_party/libpng/pngwrite.o
../third_party/libpng/pngwrite.c: In function ‘png_set_filter’:
../third_party/libpng/pngwrite.c:1010:18: warning: this statement may fall through [-Wimplicit-fallthrough=]
          case 7: png_app_error(png_ptr, "Unknown row filter for method 0");
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../third_party/libpng/pngwrite.c:1013:10: note: here
          case PNG_FILTER_VALUE_NONE:
          ^~~~
  CC(target) Release/obj.target/libpng/third_party/libpng/pngwtran.o
  CC(target) Release/obj.target/libpng/third_party/libpng/pngwutil.o
  AR(target) Release/obj.target/third_party/libpng/png.a
  COPY Release/png.a
  CC(target) Release/obj.target/zlib/third_party/zlib/adler32.o
  CC(target) Release/obj.target/zlib/third_party/zlib/compress.o
  CC(target) Release/obj.target/zlib/third_party/zlib/crc32.o
  CC(target) Release/obj.target/zlib/third_party/zlib/deflate.o
  CC(target) Release/obj.target/zlib/third_party/zlib/gzclose.o
  CC(target) Release/obj.target/zlib/third_party/zlib/gzlib.o
  CC(target) Release/obj.target/zlib/third_party/zlib/gzread.o
  CC(target) Release/obj.target/zlib/third_party/zlib/gzwrite.o
  CC(target) Release/obj.target/zlib/third_party/zlib/infback.o
../third_party/zlib/infback.c: In function ‘inflateBack’:
../third_party/zlib/infback.c:479:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = LEN;
             ~~~~~~~~~~~~^~~~~
../third_party/zlib/infback.c:481:9: note: here
         case LEN:
         ^~~~
  CC(target) Release/obj.target/zlib/third_party/zlib/inffast.o
  CC(target) Release/obj.target/zlib/third_party/zlib/inflate.o
../third_party/zlib/inflate.c: In function ‘inflateMark’:
../third_party/zlib/inflate.c:1507:61: warning: left shift of negative value [-Wshift-negative-value]
     if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                             ^~
../third_party/zlib/inflate.c: In function ‘inflate’:
../third_party/zlib/inflate.c:720:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = EXLEN;
             ~~~~~~~~~~~~^~~~~~~
../third_party/zlib/inflate.c:721:9: note: here
         case EXLEN:
         ^~~~
../third_party/zlib/inflate.c:732:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = EXTRA;
             ~~~~~~~~~~~~^~~~~~~
../third_party/zlib/inflate.c:733:9: note: here
         case EXTRA:
         ^~~~
../third_party/zlib/inflate.c:754:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = NAME;
             ~~~~~~~~~~~~^~~~~~
../third_party/zlib/inflate.c:755:9: note: here
         case NAME:
         ^~~~
../third_party/zlib/inflate.c:775:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = COMMENT;
             ~~~~~~~~~~~~^~~~~~~~~
../third_party/zlib/inflate.c:776:9: note: here
         case COMMENT:
         ^~~~
../third_party/zlib/inflate.c:795:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = HCRC;
             ~~~~~~~~~~~~^~~~~~
../third_party/zlib/inflate.c:796:9: note: here
         case HCRC:
         ^~~~
../third_party/zlib/inflate.c:818:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = DICT;
             ~~~~~~~~~~~~^~~~~~
../third_party/zlib/inflate.c:819:9: note: here
         case DICT:
         ^~~~
../third_party/zlib/inflate.c:825:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = TYPE;
             ~~~~~~~~~~~~^~~~~~
../third_party/zlib/inflate.c:826:9: note: here
         case TYPE:
         ^~~~
../third_party/zlib/inflate.c:827:16: warning: this statement may fall through [-Wimplicit-fallthrough=]
             if (flush == Z_BLOCK || flush == Z_TREES) goto inf_leave;
                ^
../third_party/zlib/inflate.c:828:9: note: here
         case TYPEDO:
         ^~~~
../third_party/zlib/inflate.c:877:16: warning: this statement may fall through [-Wimplicit-fallthrough=]
             if (flush == Z_TREES) goto inf_leave;
                ^
../third_party/zlib/inflate.c:878:9: note: here
         case COPY_:
         ^~~~
../third_party/zlib/inflate.c:879:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = COPY;
             ~~~~~~~~~~~~^~~~~~
../third_party/zlib/inflate.c:880:9: note: here
         case COPY:
         ^~~~
../third_party/zlib/inflate.c:1018:16: warning: this statement may fall through [-Wimplicit-fallthrough=]
             if (flush == Z_TREES) goto inf_leave;
                ^
../third_party/zlib/inflate.c:1019:9: note: here
         case LEN_:
         ^~~~
../third_party/zlib/inflate.c:1020:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = LEN;
             ~~~~~~~~~~~~^~~~~
../third_party/zlib/inflate.c:1021:9: note: here
         case LEN:
         ^~~~
../third_party/zlib/inflate.c:1069:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = LENEXT;
             ~~~~~~~~~~~~^~~~~~~~
../third_party/zlib/inflate.c:1070:9: note: here
         case LENEXT:
         ^~~~
../third_party/zlib/inflate.c:1079:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = DIST;
             ~~~~~~~~~~~~^~~~~~
../third_party/zlib/inflate.c:1080:9: note: here
         case DIST:
         ^~~~
../third_party/zlib/inflate.c:1106:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = DISTEXT;
             ~~~~~~~~~~~~^~~~~~~~~
../third_party/zlib/inflate.c:1107:9: note: here
         case DISTEXT:
         ^~~~
../third_party/zlib/inflate.c:1122:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = MATCH;
             ~~~~~~~~~~~~^~~~~~~
../third_party/zlib/inflate.c:1123:9: note: here
         case MATCH:
         ^~~~
../third_party/zlib/inflate.c:1197:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = LENGTH;
             ~~~~~~~~~~~~^~~~~~~~
../third_party/zlib/inflate.c:1198:9: note: here
         case LENGTH:
         ^~~~
../third_party/zlib/inflate.c:1210:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
             state->mode = DONE;
             ~~~~~~~~~~~~^~~~~~
../third_party/zlib/inflate.c:1211:9: note: here
         case DONE:
         ^~~~
  CC(target) Release/obj.target/zlib/third_party/zlib/inftrees.o
  CC(target) Release/obj.target/zlib/third_party/zlib/trees.o
  CC(target) Release/obj.target/zlib/third_party/zlib/uncompr.o
  CC(target) Release/obj.target/zlib/third_party/zlib/zutil.o
  AR(target) Release/obj.target/third_party/zlib/zlib.a
  COPY Release/zlib.a
  CXX(target) Release/obj.target/png_img/src/init.o
  CXX(target) Release/obj.target/png_img/src/PngImgAdapter.o
../src/PngImgAdapter.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE PngImgAdapter::Get(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/PngImgAdapter.cc:93:79: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Number>::return_t)’
     obj->Set(Nan::New<String>("r").ToLocalChecked(), Nan::New<Number>(pPxl->r));
                                                                               ^
In file included from /home/stefan/.cache/node-gyp/14.16.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:56,
                 from ../src/./PngImgAdapter.h:4,
                 from ../src/PngImgAdapter.cc:1:
/home/stefan/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/stefan/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/stefan/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/stefan/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
../src/PngImgAdapter.cc:94:79: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Number>::return_t)’
     obj->Set(Nan::New<String>("g").ToLocalChecked(), Nan::New<Number>(pPxl->g));
                                                                               ^
In file included from /home/stefan/.cache/node-gyp/14.16.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:56,
                 from ../src/./PngImgAdapter.h:4,
                 from ../src/PngImgAdapter.cc:1:
/home/stefan/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/stefan/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/stefan/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/stefan/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
../src/PngImgAdapter.cc:95:79: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Number>::return_t)’
     obj->Set(Nan::New<String>("b").ToLocalChecked(), Nan::New<Number>(pPxl->b));
                                                                               ^
In file included from /home/stefan/.cache/node-gyp/14.16.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:56,
                 from ../src/./PngImgAdapter.h:4,
                 from ../src/PngImgAdapter.cc:1:
/home/stefan/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/stefan/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/stefan/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/stefan/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
../src/PngImgAdapter.cc:96:79: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Number>::return_t)’
     obj->Set(Nan::New<String>("a").ToLocalChecked(), Nan::New<Number>(pPxl->a));
                                                                               ^
In file included from /home/stefan/.cache/node-gyp/14.16.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:56,
                 from ../src/./PngImgAdapter.h:4,
                 from ../src/PngImgAdapter.cc:1:
/home/stefan/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/stefan/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/stefan/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/stefan/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
../src/PngImgAdapter.cc: In lambda function:
../src/PngImgAdapter.cc:104:84: error: no matching function for call to ‘v8::Object::Get(v8::Local<v8::String>)’
         Nan::Utf8String val(obj->Get(Nan::New<String>(key.c_str()).ToLocalChecked()));
                                                                                    ^
In file included from /home/stefan/.cache/node-gyp/14.16.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:56,
                 from ../src/./PngImgAdapter.h:4,
                 from ../src/PngImgAdapter.cc:1:
/home/stefan/.cache/node-gyp/14.16.0/include/node/v8.h:3717:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                           ^~~
/home/stefan/.cache/node-gyp/14.16.0/include/node/v8.h:3717:43: note:   candidate expects 2 arguments, 1 provided
/home/stefan/.cache/node-gyp/14.16.0/include/node/v8.h:3720:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                           ^~~
/home/stefan/.cache/node-gyp/14.16.0/include/node/v8.h:3720:43: note:   candidate expects 2 arguments, 1 provided
png_img.target.mk:120: recipe for target 'Release/obj.target/png_img/src/PngImgAdapter.o' failed
make: Leaving directory '/home/stefan/git/digitransit-ui/node_modules/png-img/build'
make: *** [Release/obj.target/png_img/src/PngImgAdapter.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/stefan/git/digitransit-ui/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 4.15.0-140-generic
gyp ERR! command "/home/stefan/.nvm/versions/node/v14.16.0/bin/node" "/home/stefan/git/digitransit-ui/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/stefan/git/digitransit-ui/node_modules/png-img
```

**Comment by optionsome** [comment]
Currently the supported node version is  >= 10.19 but as stated in Installation.md, versions higher than that don't most likely work. We will try to add support for more modern node versions at some point when we have time.

**Comment by dancesWithCycles** [comment]
Hi @optionsome ,
Thank you very much for the clarification about the node version. I though the ```>= 10.19``` requirement is a bit more flexible. However, now that I know better I was able to run ```yarn install``` successfully with node version ```v10.23.0```.

Cheers!
