### ISSUE TITLE
Unable to yarn run build according to Installation.md

### ISSUE THREAD

**Issue by dancesWithCycles** [HSLdevcom/digitransit-ui#4179]
Hi folks,
How are you doing? It is me again. Last time I had difficulties running `yarn install`. Now, this one is solved, I ran into another difficulty.

I am following the `Installation.md` documentation with the goal to build and run a customized version of digitransit-ui.

My build environment is the following.

```
~/git/digitransit-ui$ node -v
v10.23.0
~/git/digitransit-ui$ npm -v
7.5.4
~/git/digitransit-ui$ yarn --version
1.22.10
~/git/digitransit-ui$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6)
```

When I call the instruction `yarn run build` I receive the following error. I appreciate any advice pointing me in the right direction. Cheers!

```
yarn run v1.22.10
$ yarn run static
$ mkdir -p _static/js; mkdir -p _static/css; cp -r static/* _static
$ NODE_ENV=production node --max_old_space_size=4096 node_modules/.bin/webpack --progress --color --display-error-details
10% building 1/1 modules 0 activeError: Module build failed (from ./node_modules/favicons-webpack-plugin/lib/favicons.js):
Error: Command failed: /home/user/GitHub/dancesWithCycles/digitransit-ui/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs /home/user/GitHub/dancesWithCycles/digitransit-ui/node_modules/svg2png/lib/converter.js {"height":512,"width":512}
Auto configuration failed
140373889871488:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
140373889871488:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140373889871488:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
140373889871488:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf

    at ChildProcess.exithandler (child_process.js:294:12)
    at Object.apply (/home/user/GitHub/dancesWithCycles/digitransit-ui/node_modules/harmony-reflect/reflect.js:2064:37)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Object.apply (/home/user/GitHub/dancesWithCycles/digitransit-ui/node_modules/harmony-reflect/reflect.js:2064:37)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
    at Object../node_modules/favicons-webpack-plugin/lib/favicons.js?{"outputFilePrefix":"assets/icons-hsl-[hash]/","icons":{"android":true,"appleIcon":true,"appleStartup":true,"coast":false,"favicons":true,"firefox":true,"opengraph":false,"twitter":false,"yandex":false,"windows":false},"background":"#eef1f3","persistentCache":true,"appName":"Reittiopas"}!./app/configurations/images/hsl/icon_favicon-reittiopas.svg (eval at <anonymous> (/home/user/GitHub/dancesWithCycles/digitransit-ui/node_modules/favicons-webpack-plugin/lib/compiler.js:56:22), <anonymous>:92:7)
    at __webpack_require__ (eval at <anonymous> (/home/user/GitHub/dancesWithCycles/digitransit-ui/node_modules/favicons-webpack-plugin/lib/compiler.js:56:22), <anonymous>:20:30)
    at ./node_modules/favicons-webpack-plugin/lib/favicons.js?{"outputFilePrefix":"assets/icons-hsl-[hash]/","icons":{"android":true,"appleIcon":true,"appleStartup":true,"coast":false,"favicons":true,"firefox":true,"opengraph":false,"twitter":false,"yandex":false,"windows":false},"background":"#eef1f3","persistentCache":true,"appName":"Reittiopas"}!./app/configurations/images/hsl/icon_favicon-reittiopas.svg (eval at <anonymous> (/home/user/GitHub/dancesWithCycles/digitransit-ui/node_modules/favicons-webpack-plugin/lib/compiler.js:56:22), <anonymous>:84:18)
    at eval (eval at <anonymous> (/home/user/GitHub/dancesWithCycles/digitransit-ui/node_modules/favicons-webpack-plugin/lib/compiler.js:56:22), <anonymous>:87:10)
    at /home/user/GitHub/dancesWithCycles/digitransit-ui/node_modules/favicons-webpack-plugin/lib/compiler.js:56:22
    at _next1 (eval at create (/home/user/GitHub/dancesWithCycles/digitransit-ui/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at _promise1.then._result1 (eval at create (/home/user/GitHub/dancesWithCycles/digitransit-ui/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by dancesWithCycles** [comment]
Hi folks,
according to the Internet, there is an issue on Debian operating systems with the phantomjs npm package. The following links provide more information.

https://github.com/ariya/phantomjs/issues/15449

https://stackoverflow.com/questions/53355217/genymotion-throws-libssl-conf-so-cannot-open-shared-object-file-no-such-file-o

I chose a shot-term workaround to execute `yarn run build`.

I exported the environment variable `OPENSSL_CONF` in the following way.

```
export OPENSSL_CONF=/etc/ssl/
```

I hope this helps someone facing the same issue. Cheers!
